version: '3'
services:
  wiki:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: capstone_password
    networks:
      - backend

networks:
  frontend:
  backend:
